### ISSUE TITLE
Simulation erstellen mit trains, schedules, rail segments, and a rail network

### ISSUE THREAD

**Issue by tobi1196** [tobi1196/INFORE3#25]

**Comment by tobi1196** [comment]
Wird mit #24 bearbeitet

**Comment by adrianstarkbaum** [comment]
Nach Aufgabe:

create a simulation consisting of trains, schedules, rail segments, and a rail network; the network consists of a five rail segments that each has a capacity for three trains, each train has a schedule which determines on which segment it wants to drive; implement a single simulation step (which is supposed to represent a quarter hour), where:

    each individual train announces on which segment it wants to drive based on its schedule
    the network tallies up the number of trains on each segment and compares it to the capacity
    the network decides for each train whether it drives or is delayed due to the segment being at maximum capacity:
        less than or equal to capacity ~> all trains drive
        over capacity ~> all trains are delayed

**Comment by adrianstarkbaum** [comment]
Wurde mit dem merge von #24 abgeschlossen
