### ISSUE TITLE
Travis integrieren

### ISSUE THREAD

**Issue by adrianstarkbaum** [tobi1196/INFORE3#7]
Parlog im Issue markieren, sodass er Travis hinzufügen kann.

**Comment by tobi1196** [comment]
@nicolaiparlog Sie können Travis hinzufügen

**Comment by nipafx** [comment]
Erst wenn #16 gemergt ist.

**Comment by adrianstarkbaum** [comment]
#16 wurde gemergt, @nicolaiparlog können Sie nun travis hinzufügen?

**Comment by nipafx** [comment]
@tobi1196 muss Travis anschmeißen. Dazu bitte Schritte 1 und 2 [aus dieser Anleitung](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich konfiguriere Travis dann.

**Comment by tobi1196** [comment]
@nicolaiparlog wurde erledigt
